FROM node:22-alpine
WORKDIR /app
COPY --chown=root:root --chmod=755 package*.json ./
RUN npm install --ignore-scripts
RUN chown -R node:node node_modules
COPY --chown=root:root --chmod=755 src ./src
COPY --chown=root:root --chmod=755 public ./public
COPY --chown=root:root --chmod=755 index.html vite.config.ts tsconfig*.json ./
COPY --chown=root:root --chmod=755 eslint.config.js components.json ./
COPY --chown=root:root --chmod=755 .env* ./
USER node
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host"]
